from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query

from noteclaw_backend.domain.enums import ContentType, NoteStatus
from noteclaw_backend.schemas.common import ApiMessage, new_id, utc_now
from noteclaw_backend.schemas.knowledge import (
    FeedbackRequest,
    FeedbackResponse,
    KnowledgeListResponse,
    NoteDetail,
    NoteListItem,
    NoteUpdateRequest,
)


router = APIRouter()


@router.get("", response_model=KnowledgeListResponse)
async def list_knowledge(
    q: str | None = None,
    content_type: ContentType | None = None,
    tag: list[str] = Query(default_factory=list),
    category: str | None = None,
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
) -> KnowledgeListResponse:
    now = utc_now()
    item = NoteListItem(
        id="note_stub",
        title="Knowledge repository placeholder",
        content_type=content_type or ContentType.TEXT,
        summary="SQLite-backed knowledge listing is pending.",
        tags=tag or ["stub"],
        category=category,
        source="system",
        status=NoteStatus.READY,
        created_at=now,
        updated_at=now,
    )
    return KnowledgeListResponse(items=[item], total=1, limit=limit, offset=offset)


@router.get("/{note_id}", response_model=NoteDetail)
async def get_knowledge(note_id: str) -> NoteDetail:
    if not note_id:
        raise HTTPException(status_code=404, detail="Note not found")
    now = utc_now()
    return NoteDetail(
        id=note_id,
        title="Knowledge detail placeholder",
        content_type=ContentType.TEXT,
        content="Original content will be loaded from SQLite.",
        summary="Summary will be generated by the LLM provider.",
        tags=["stub"],
        category="system",
        source="system",
        status=NoteStatus.READY,
        chunks=[],
        metadata={"storage": "sqlite_pending"},
        created_at=now,
        updated_at=now,
    )


@router.patch("/{note_id}", response_model=NoteDetail)
async def update_knowledge(note_id: str, request: NoteUpdateRequest) -> NoteDetail:
    now = utc_now()
    return NoteDetail(
        id=note_id,
        title=request.title or "Updated knowledge placeholder",
        content_type=ContentType.TEXT,
        content="Original content remains unchanged.",
        summary=request.summary,
        tags=request.tags or [],
        category=request.category,
        source="system",
        status=NoteStatus.READY,
        chunks=[],
        metadata={"update": "sqlite_pending"},
        created_at=now,
        updated_at=now,
    )


@router.delete("/{note_id}", response_model=ApiMessage)
async def delete_knowledge(note_id: str) -> ApiMessage:
    return ApiMessage(message=f"Delete accepted for {note_id}; SQLite/FAISS deletion pending.")


@router.post("/{note_id}/feedback", response_model=FeedbackResponse)
async def create_feedback(note_id: str, request: FeedbackRequest) -> FeedbackResponse:
    _ = request
    return FeedbackResponse(
        note_id=note_id or new_id("note"),
        accepted=True,
        message="Feedback accepted. Personalization storage pending.",
    )
