"""Render slide outline + layout decision into complete HTML using Jinja2 templates."""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates" / "slides"


@lru_cache(maxsize=1)
def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        autoescape=select_autoescape(default=True),
        trim_blocks=True,
        lstrip_blocks=True,
    )


def render_slide_html(
    slide: dict[str, Any],
    layout: dict[str, Any],
    deck_meta: dict[str, Any],
    slide_index: int,
) -> str:
    """Render a slide to a complete HTML document string."""
    template_name = f"{layout.get('template', 'bullets')}.html.j2"
    try:
        template = _env().get_template(template_name)
    except Exception:
        template = _env().get_template("bullets.html.j2")

    context = _build_context(slide, layout, deck_meta, slide_index)
    return template.render(**context)


def _build_context(
    slide: dict[str, Any],
    layout: dict[str, Any],
    deck_meta: dict[str, Any],
    slide_index: int,
) -> dict[str, Any]:
    template = layout.get("template", "bullets")
    text_budget = int(layout.get("text_budget") or 600)
    body_size = int(layout.get("body_size") or 22)
    params = layout.get("params") or {}

    title = str(slide.get("title") or "Untitled")[:140]
    bullets_raw = slide.get("bullets") or slide.get("points") or []
    if isinstance(bullets_raw, str):
        bullets_raw = [bullets_raw]
    bullets = [_bullet_object(b, text_budget) for b in bullets_raw][:6]

    ctx: dict[str, Any] = {
        "title": title,
        "index": slide_index,
        "deck_label": deck_meta.get("label") or deck_meta.get("title") or "NoteClaw Deck",
        "author": deck_meta.get("author") or "Generated by NoteClaw",
        "body_size": body_size,
        "font_size": 56 if len(title) <= 24 else (48 if len(title) <= 40 else 38),
    }

    if template == "title":
        ctx["subtitle"] = params.get("subtitle") or slide.get("subtitle") or ""
        if deck_meta.get("title"):
            ctx["deck_label"] = deck_meta["label"] or deck_meta["title"]
    elif template == "quote":
        primary_bullet = bullets[0] if bullets else {"heading": title, "text": ""}
        ctx["quote"] = (primary_bullet.get("text") or title)[:600]
        ctx["quote_size"] = 38 if len(ctx["quote"]) < 120 else 30
        ctx["attribution"] = params.get("attribution") or ""
    elif template == "two_column":
        left_items = params.get("left_items") or [_strip_header(b) for b in bullets[:2]]
        right_items = params.get("right_items") or [_strip_header(b) for b in bullets[2:4]]
        ctx["left_title"] = params.get("left_title") or "Aspect A"
        ctx["right_title"] = params.get("right_title") or "Aspect B"
        ctx["left_items"] = [_truncate(item, text_budget) for item in left_items][:5]
        ctx["right_items"] = [_truncate(item, text_budget) for item in right_items][:5]
    else:  # bullets
        ctx["bullets"] = bullets

    return ctx


def _bullet_object(raw: Any, budget: int) -> dict[str, str]:
    if isinstance(raw, dict):
        heading = str(raw.get("heading") or raw.get("title") or "").strip()
        text = str(raw.get("text") or raw.get("description") or "").strip()
        desc = str(raw.get("description") or "").strip()
    else:
        s = str(raw).strip()
        if ":" in s and s.split(":", 1)[0].count(" ") <= 4:
            head, rest = s.split(":", 1)
            heading, text, desc = head.strip(), rest.strip(), ""
        else:
            heading, text, desc = "", s, ""
    return {
        "heading": heading[:120],
        "text": _truncate(text, budget),
        "description": _truncate(desc, budget),
    }


def _strip_header(bullet: dict[str, str]) -> str:
    parts = [bullet.get("heading"), bullet.get("text")]
    return " ".join(p for p in parts if p)


def _truncate(text: str, limit: int) -> str:
    s = (text or "").strip()
    if len(s) <= limit:
        return s
    cut = s.rfind(" ", 0, limit)
    return (s[: cut] if cut > limit // 2 else s[:limit]).rstrip() + "…"
